/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;
 
import ProyectoFinal.NuevaOrden;
import ProyectoFinal.Ordenador;
import ProyectoFinal.Precios;
import javax.swing.JOptionPane;

/**
 *
 * @author barbaspc
 */
public class IngresarNuevasActividades extends javax.swing.JFrame {


    boolean[] arregloEstadosCheck = new boolean[29];
    int[] arregloIterador = new int[1];
    public int presupuestoPreliminar = 0;
    private int flag = 0, flag2 = 0;

    /**
     * Creates new form IngresarNuevasActividades
     */

    public static IngresarNuevasActividades ingresarkdvMysql = new IngresarNuevasActividades();

    public void IngresarNuevasActividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BarbasPC - Seleccionar Servicios");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox1.setText("Formateo(Cualquier SO)");

        jCheckBox2.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox2.setText("Reparar inicio Windows");

        jCheckBox3.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox3.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox3.setText("Instalación de drivers");

        jCheckBox4.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox4.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox4.setText("Eliminación de malware");

        jCheckBox5.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox5.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox5.setText("Eliminación contraseña");

        jCheckBox6.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox6.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox6.setText("Cifrado BIOS");

        jCheckBox7.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox7.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox7.setText("Cifrado USB/HDD/SDD");

        jCheckBox8.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox8.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox8.setText("Programa free");

        jCheckBox9.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox9.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox9.setText("Programa comercial");

        jCheckBox10.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox10.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox10.setText("Optimizacion");

        jCheckBox11.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox11.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox11.setText("Inmunización USB");

        jCheckBox12.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox12.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox12.setText("Revisión Interna");

        jCheckBox13.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox13.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox13.setText("Cambio HDD/SDD");

        jCheckBox14.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox14.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox14.setText("Cambio memorias RAM");

        jCheckBox15.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox15.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox15.setText("Cambio motherboard");

        jCheckBox16.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox16.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox16.setText("Cambio de gabinete");

        jCheckBox17.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox17.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox17.setText("Cambio ventilador");

        jCheckBox18.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox18.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox18.setText("Cambio pasta térmica");

        jCheckBox19.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox19.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox19.setText("Lubricación ventiladores");

        jCheckBox20.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox20.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox20.setText("Limpieza externa");

        jCheckBox21.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox21.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox21.setText("Limpieza con aire compr.");

        jCheckBox22.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox22.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox22.setText("Cambio unidades ópticas");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });

        jCheckBox23.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox23.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox23.setText("Cambio de correa lectora");

        jCheckBox24.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox24.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox24.setText("Cambio de fuente");

        jCheckBox25.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox25.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox25.setText("Cambio ventilador fuente");

        jCheckBox26.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox26.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox26.setText("Cambio capacitores fuente");

        jCheckBox27.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox27.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox27.setText("Instalación de placas");

        jCheckBox28.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox28.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox28.setText("Limpieza placa video");

        jCheckBox29.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox29.setForeground(new java.awt.Color(0, 255, 255));
        jCheckBox29.setText("Cambio capacitores mother");

        jButton1.setText("Generar presupuesto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Guardar presupuesto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox10)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox11)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox12)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox3)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox13)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox4)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox14)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox5)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox15)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox6)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox16)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox7)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox17)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox8)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox18)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox9)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox19)
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox29))
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCheckBox1, jCheckBox10, jCheckBox11, jCheckBox12, jCheckBox13, jCheckBox14, jCheckBox15, jCheckBox16, jCheckBox17, jCheckBox18, jCheckBox19, jCheckBox2, jCheckBox20, jCheckBox21, jCheckBox22, jCheckBox23, jCheckBox24, jCheckBox25, jCheckBox26, jCheckBox27, jCheckBox28, jCheckBox29, jCheckBox3, jCheckBox4, jCheckBox5, jCheckBox6, jCheckBox7, jCheckBox8, jCheckBox9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox26))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jLabel1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void generarPresupuesto(){

      flag2 = 1;
    // <editor-fold defaultstate="collapsed" desc="Checkbox 1-29">
      if(jCheckBox1.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[0].costo;
      }
      if(jCheckBox2.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[1].costo;
      }
      if(jCheckBox3.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[2].costo;
      }
      if(jCheckBox4.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[3].costo;
      }
      if(jCheckBox5.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[4].costo;
      }
      if(jCheckBox6.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[5].costo;
      }
      if(jCheckBox7.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[6].costo;
      }
      if(jCheckBox8.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[7].costo;
      }
      if(jCheckBox9.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[8].costo;
      }
      if(jCheckBox10.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[9].costo;
      }
      if(jCheckBox11.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[10].costo;
      }
      if(jCheckBox12.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[11].costo;
      }
      if(jCheckBox13.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[12].costo;
      }
      if(jCheckBox14.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[13].costo;
      }
      if(jCheckBox15.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[14].costo;
      }
      if(jCheckBox16.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[15].costo;
      }
      if(jCheckBox17.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[16].costo;
      }
      if(jCheckBox18.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[17].costo;
      }
      if(jCheckBox19.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[18].costo;
      }
      if(jCheckBox20.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[19].costo;
      }
      if(jCheckBox21.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[20].costo;
      }
      if(jCheckBox22.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[21].costo;
      }
      if(jCheckBox23.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[22].costo;
      }
      if(jCheckBox24.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[23].costo;
      }
      if(jCheckBox25.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[24].costo;
      }
      if(jCheckBox26.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[25].costo;
      }
      if(jCheckBox27.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[26].costo;
      }
      if(jCheckBox28.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[27].costo;
      }
      if(jCheckBox29.isSelected()){
          presupuestoPreliminar =  presupuestoPreliminar + Precios.servicios[28].costo;
      }
        // </editor-fold>
    }

    public void limpiarCheckBox(){
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        jCheckBox12.setSelected(false);
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
        jCheckBox16.setSelected(false);
        jCheckBox17.setSelected(false);
        jCheckBox18.setSelected(false);
        jCheckBox19.setSelected(false);
        jCheckBox20.setSelected(false);
        jCheckBox21.setSelected(false);
        jCheckBox22.setSelected(false);
        jCheckBox23.setSelected(false);
        jCheckBox24.setSelected(false);
        jCheckBox25.setSelected(false);
        jCheckBox26.setSelected(false);
        jCheckBox27.setSelected(false);
        jCheckBox28.setSelected(false);
        jCheckBox29.setSelected(false);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        presupuestoPreliminar = 0;
        generarPresupuesto();
        jLabel1.setText("Presupuesto preliminar: $"+presupuestoPreliminar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(flag2 == 1){
            Ordenador.ordenadores.equipos[Ordenador.l].presupuestoFinal(presupuestoPreliminar);
            ingresarkdvMysql.setVisible(false);
            flag2 = 0;

           // NuevaOrden.nuevasordenes.mostrarDatos();
            if(flag == 0){
                DatosOrden.datosorden.DatosOrden();
                DatosOrden.datosorden.setVisible(true);
                DatosOrden.datosorden.setText();
            flag = 1;
            }
            else{
                DatosOrden.datosorden.setVisible(true);
                DatosOrden.datosorden.setText();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Genere presupuesto preliminar antes de continuar");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevasActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevasActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevasActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarNuevasActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarNuevasActividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
